/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROJEKT_PROTOKOL_PB_H_INCLUDED
#define PB_PROJEKT_PROTOKOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _StationInfo {
    char name[32];
    uint32_t id;
} StationInfo;

typedef struct _SensorReport {
    bool has_station;
    StationInfo station;
    float temperature;
    float humidity;
    int32_t light_level;
} SensorReport;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define StationInfo_init_default                 {"", 0}
#define SensorReport_init_default                {false, StationInfo_init_default, 0, 0, 0}
#define StationInfo_init_zero                    {"", 0}
#define SensorReport_init_zero                   {false, StationInfo_init_zero, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define StationInfo_name_tag                     1
#define StationInfo_id_tag                       2
#define SensorReport_station_tag                 1
#define SensorReport_temperature_tag             2
#define SensorReport_humidity_tag                3
#define SensorReport_light_level_tag             4

/* Struct field encoding specification for nanopb */
#define StationInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   id,                2)
#define StationInfo_CALLBACK NULL
#define StationInfo_DEFAULT NULL

#define SensorReport_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  station,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          3) \
X(a, STATIC,   SINGULAR, INT32,    light_level,       4)
#define SensorReport_CALLBACK NULL
#define SensorReport_DEFAULT NULL
#define SensorReport_station_MSGTYPE StationInfo

extern const pb_msgdesc_t StationInfo_msg;
extern const pb_msgdesc_t SensorReport_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define StationInfo_fields &StationInfo_msg
#define SensorReport_fields &SensorReport_msg

/* Maximum encoded size of messages (where known) */
#define PROJEKT_PROTOKOL_PB_H_MAX_SIZE           SensorReport_size
#define SensorReport_size                        62
#define StationInfo_size                         39

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
